
package licencias.GUIs;

import Entidades.Impresion;
import Entidades.ImprimirLicencia;
import Entidades.Licencia;
import Entidades.Titular;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.print.Printable;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.EntityTransaction;
import javax.persistence.Query;
import licencias.Imagen;
import licencias.ImagenImprimir;

public class Fm_Imprimir extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form Fm_Imprimir
     */
    int un_id_licencia;
    
    public Fm_Imprimir(){
        initComponents();
    }
    
    public Fm_Imprimir(int id_licencia){
        initComponents();
        
        un_id_licencia = id_licencia;
        
        Licencia l = getLicencia(id_licencia);
        Titular t = getTitular(l.getIdTitular());
        
        jlClase.setText(l.getClase());
        jlApellido.setText(t.getApellido());
        jlNombre.setText(t.getNombre());
        jlTipo.setText(t.getTipoDocumento());
        jlDocumento.setText(t.getNroDocumento());
        jlDireccion.setText(t.getDireccion());
        if(t.getEsDonante()){
        jlDonante.setText("Si");
        }
        else{
        jlDonante.setText("No");
        
        }
        jlGrupoFact.setText(t.getGrupoSanguineo()+" "+t.getFactorRh());
        jlObs.setText(l.getObservacion());
        
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String dateStringAlta = formatter.format(l.getFechaAlta());
        String dateStringVigencia = formatter.format(l.getVigencia());
        
        jlFechaAlta.setText(dateStringAlta);
        jlvencimiento.setText(dateStringVigencia);
        
        ImagenImprimir im = new ImagenImprimir(jpImagen,t.getRutaImagen());
        jpImagen.add(im).repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("licencias?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        titularQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Titular t");
        titularList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : titularQuery.getResultList();
        impresionQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT i FROM Impresion i");
        impresionList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : impresionQuery.getResultList();
        impresionQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT i FROM Impresion i");
        impresionList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : impresionQuery1.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jbImprimir = new javax.swing.JButton();
        jpImprimir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlClase = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpImagen = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jlDocumento = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlDireccion = new javax.swing.JLabel();
        jlDonante = new javax.swing.JLabel();
        jlGrupoFact = new javax.swing.JLabel();
        jlObs = new javax.swing.JLabel();
        jlFechaAlta = new javax.swing.JLabel();
        jlvencimiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbImprimir.setText("Imprimir");
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbImprimir)
                .addGap(259, 259, 259))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbImprimir)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Apellido:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Dirección:");

        jlClase.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlClase.setText("Clase");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Fecha Alta:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Vencimiento:");

        jpImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jpImagenLayout = new javax.swing.GroupLayout(jpImagen);
        jpImagen.setLayout(jpImagenLayout);
        jpImagenLayout.setHorizontalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jpImagenLayout.setVerticalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Observación:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Es Donante:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Grupo y Factor:");

        jlTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTipo.setForeground(new java.awt.Color(1, 10, 100));
        jlTipo.setText("Tipo");

        jlDocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlDocumento.setForeground(new java.awt.Color(1, 10, 100));
        jlDocumento.setText("Número Documento");

        jlApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlApellido.setForeground(new java.awt.Color(1, 10, 100));
        jlApellido.setText("Apellido");

        jlNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(1, 10, 100));
        jlNombre.setText("Nombre");

        jlDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDireccion.setForeground(new java.awt.Color(1, 10, 100));
        jlDireccion.setText("Dirección");

        jlDonante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDonante.setForeground(new java.awt.Color(1, 10, 100));
        jlDonante.setText("Donante");

        jlGrupoFact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlGrupoFact.setForeground(new java.awt.Color(1, 10, 100));
        jlGrupoFact.setText("Grupo y Factor");

        jlObs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlObs.setForeground(new java.awt.Color(1, 10, 100));
        jlObs.setText("Observación");

        jlFechaAlta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlFechaAlta.setForeground(new java.awt.Color(1, 10, 100));
        jlFechaAlta.setText("Fecha Alta");

        jlvencimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlvencimiento.setForeground(new java.awt.Color(1, 10, 100));
        jlvencimiento.setText("Vencimiento");

        javax.swing.GroupLayout jpImprimirLayout = new javax.swing.GroupLayout(jpImprimir);
        jpImprimir.setLayout(jpImprimirLayout);
        jpImprimirLayout.setHorizontalGroup(
            jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImprimirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpImprimirLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpImprimirLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNombre))
                            .addGroup(jpImprimirLayout.createSequentialGroup()
                                .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlClase)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlApellido)))
                        .addContainerGap(286, Short.MAX_VALUE))
                    .addGroup(jpImprimirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpImprimirLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlFechaAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jpImprimirLayout.createSequentialGroup()
                                .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpImprimirLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jlTipo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlDocumento))
                                    .addGroup(jpImprimirLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlDonante)
                                            .addComponent(jlDireccion)
                                            .addComponent(jlGrupoFact)
                                            .addComponent(jlObs))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlvencimiento)
                        .addGap(68, 68, 68))))
        );
        jpImprimirLayout.setVerticalGroup(
            jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImprimirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpImprimirLayout.createSequentialGroup()
                        .addComponent(jlClase)
                        .addGap(18, 18, 18)
                        .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jlApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jlNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTipo)
                            .addComponent(jlDocumento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlDireccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDonante)
                            .addComponent(jLabel8)))
                    .addComponent(jpImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jlGrupoFact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlObs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlFechaAlta)
                    .addComponent(jLabel6)
                    .addComponent(jlvencimiento))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Obtener datos de la licencia
    private Licencia getLicencia(int id_licencia){
        
    Licencia lic = new Licencia();
        
        Query q = entityManager.createQuery("select l from Licencia L where l.idLicencia=?1");
        q.setParameter(1, id_licencia);
        if(q.getFirstResult() ==0)
        {
            lic = (Licencia)q.getSingleResult();
        }
        return lic;
    }
    
    //Obtener datos del titular
    private Titular getTitular(int id_titular){
        Titular titu = new Titular();
        
        Query q = entityManager.createQuery("select t from Titular T where t.activo = true and t.idTitular=?1");
        q.setParameter(1, id_titular);
        if(q.getFirstResult() ==0)
        {
            titu = (Titular)q.getSingleResult();
        }
        return titu;
    }
    
    //Colocar el true el bit de licencia impresa
      private void actualizarLicencia(int id_licencia){
        Licencia lic = entityManager.find(Licencia.class,id_licencia);
        lic.setImpresa(true);
        
        EntityTransaction etx = entityManager.getTransaction();
        etx.begin();
        //entityManager.close();
        etx.commit();
        
    }
      
      //Guardar impresión y log
    private void guardarImpresion(int id_licencia){
        Impresion imp = new Impresion();
        imp.setFecha(new Date());
        imp.setIdLicencia(id_licencia);
        imp.setNroCopia(1);
       
        EntityTransaction etx = entityManager.getTransaction();
        etx.begin();
        entityManager.persist(imp);
        
      etx.commit();
        
    }
    
    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed
        try {
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable(this);
            job.printDialog();
            job.print();
            guardarImpresion(un_id_licencia);
            actualizarLicencia(un_id_licencia);
            
            dispose();
} catch (PrinterException ex) {
  
}
    }//GEN-LAST:event_jbImprimirActionPerformed

   public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
   if (pageIndex > 0) { /* We have only one page, and 'page' is zero-based */
      return NO_SUCH_PAGE;
   }
   Graphics2D g2d = (Graphics2D)graphics;
   g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
   jpImprimir.printAll(graphics);

return PAGE_EXISTS;

}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fm_Imprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fm_Imprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fm_Imprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fm_Imprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fm_Imprimir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private java.util.List<Entidades.Impresion> impresionList;
    private java.util.List<Entidades.Impresion> impresionList1;
    private javax.persistence.Query impresionQuery;
    private javax.persistence.Query impresionQuery1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlClase;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlDocumento;
    private javax.swing.JLabel jlDonante;
    private javax.swing.JLabel jlFechaAlta;
    private javax.swing.JLabel jlGrupoFact;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlObs;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlvencimiento;
    private javax.swing.JPanel jpImagen;
    private javax.swing.JPanel jpImprimir;
    private java.util.List<Entidades.Titular> titularList;
    private javax.persistence.Query titularQuery;
    // End of variables declaration//GEN-END:variables
}
